finished milestone 1
hack4impact-calpoly/bootcamp-project-2022 pull request #44
Opened 2022-10-24 06:58 UTC by nnayk

# Milestone: 1
# Developer: Nakul Nayak

### Pull Request Summary
This is my recipe site for milestone 1.

{Describe the purpose of your pull request}

### Pull Request Checklist
- [ X] Code is neat, readable, and works
- [ X] Comments are appropriate
- [X ] The commit message follows our guidelines
- [ X] The milestone number is specified
- [ X] The developer name is specified
- [ X] The summary is completed

### Reviewer Checklist  - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual template contributor, do not fill out the rest of the fields or check the boxes.

NOTE: Milestones can only be completed when all boxes are checked.

- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Comment that you have reviewed the code
- [ ] This box is checked

2022-11-01 20:31 UTC, vwinstea commented
Make sure to add all of your new files before committing them, right now you have no files committed. It looks like you have another repo nested inside your milestone repo. This stackoverflow page may help: [https://stackoverflow.com/questions/62056294/github-folders-have-a-white-arrow-on-them](https://stackoverflow.com/questions/62056294/github-folders-have-a-white-arrow-on-them). Please reach out if you have any questions!

2022-11-01 21:14 UTC, nnayk commented
sorry about that, I've pushed the files now.

2022-11-02 17:21 UTC, vwinstea requested changes
Good progress, but there are a few things I think you should change before porting wrapping up this milestone:

- [ ] Add more CSS to your about page and recipe page: more color, different fonts from the default, and adjusting the positioning between some content are all good first steps
- [ ] Some pages are missing content: the homepage should include recipe descriptions and each recipe page should have an image
- [ ] I left some comments on places in your code where things were commented out or not doing anything. Please reach out if you want help fixing those, otherwise just delete the commented out code

Please reach out on this PR or via slack if you have any questions or concerns. Good luck wrapping up this milestone!

2022-11-02 17:21 UTC, vwinstea commented on about.css
> +    /* justify-content: space-around; */
Delete commented out rules. If you were having issues with flexbox here just lmk and I'll see if I can help!

2022-11-02 17:21 UTC, vwinstea commented on about.html
> +        <p class="logo"><strong></strong></p>
Let me know if you need help positioning a logo!

2022-11-02 17:21 UTC, vwinstea commented on index.html
> +        </div>
Use the `<header>` tag to denote where the header is instead of the `<div>` you are currently using

2022-11-02 17:21 UTC, vwinstea commented on index.html
> +        </div>
Also, you might want to move your navbar out of the "block-one" div so the navbar looks the same across all your pages. Right now, it's positioned differently on your homepage

2022-11-02 17:21 UTC, vwinstea commented on biryani.html
> +    <h2>Ingredients</h2>
Recipe pages should include an image

2022-11-11 06:35 UTC, nnayk commented
I've been quite busy this quarter so apologies for the delays...I updated the code based on the feedback. I wasn't able to fix the header issue in this milestone but I was able to do so for milestone 3

2022-11-11 06:49 UTC, nnayk commented
Since my milestone 1 pull request is still pending, I'm not sure how to access the pull request for milestone 3 right now.

2022-11-13 16:29 UTC, vwinstea reviewed
Great work, thanks for getting those changes in! It's looking a lot better between the added content, cleaned up code, and added styling. Moving forwards, I would recommend pushing yourself a bit more on CSS, especially with more flexbox/layout stuff. The CSS is fine for this milestone though. Overall it's looking good though!

2022-11-13 16:30 UTC, vwinstea commented
Milestone 1 complete! You should be able to make a new PR for milestone 3 now.

2022-11-13 16:30 UTC, closed without merging